name: pruebalocomotion
favicon: null
layout_spectrum: 0.5678363055922091
typography_spectrum: 0.015385486651211977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.47311970219016075
  lightness: 0.2498980003874749
  saturation: 0.704353483626619
  rhythmicContrast: 0.42178009334020317
purpose: []
