name: pruebalocomotion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0b1e'
    - '#6267a4'
    - '#35418e'
    - '#8a96c3'
    - '#bbbbce'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
